{% set name = "xlntpyarrow" %}
{% set version = "1.5.0" %}
{% set sha256 = "be64639011d119dfda7dfc649fd951624277106b708be3e3a761fefd119e4d2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: dev.zip
  url: https://github.com/tfussell/xlnt/archive/dev.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - python
    - toolchain
    - cmake
    - pyarrow
  run:
    - python
    - pyarrow

test:
  imports:
    - xlntpyarrow

about:
  home: https://github.com/tfussell/xlnt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: C++ XLSX library
  dev_url: https://github.com/tfussell/xlnt

extra:
  recipe-maintainers:
    - tfussell
