{% set name = "xlntpyarrow" %}
{% set version = "1.2.0" %}
{% set sha256 = "38196ce9566940dffdd3db8061419a747266509555cc0f696e06fb142e1cf58a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: dev.zip
  url: https://github.com/tfussell/xlnt/archive/dev.zip
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pyarrow
  run:
    - python
    - pyarrow

test:
  imports:
    - xlntpyarrow

about:
  home: https://github.com/tfussell/xlnt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'C++ XLSX library'
  dev_url: https://github.com/tfussell/xlnt

extra:
  recipe-maintainers:
    - tfussell
