{% set name = "xlntpyarrow" %}
{% set version = "1.2.0" %}
{% set sha256 = "ecbf7cca0a0b0df7dcc90c650acf8417fa992eda8f2477f7b11b6872650c8f73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: dev.zip
  url: https://github.com/tfussell/xlnt/archive/dev.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  build:
    - python
    - toolchain
    - cmake
    - pyarrow
  run:
    - python
    - pyarrow

test:
  imports:
    - xlntpyarrow

about:
  home: https://github.com/tfussell/xlnt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'C++ XLSX library'
  dev_url: https://github.com/tfussell/xlnt

extra:
  recipe-maintainers:
    - tfussell
