{% set name = "xlntpyarrow" %}
{% set version = "1.2.0" %}
{% set sha256 = "6d099e0cf0688692bdc2e53c6e03e998267bc196ffef13804d40340b7922963b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: dev.zip
  url: https://github.com/tfussell/xlnt/archive/dev.zip
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win32]
  skip: true  # [win and py<35]

requirements:
  host:
    - python
    - toolchain
    - cmake
    - pyarrow
  run:
    - python
    - pyarrow

test:
  imports:
    - xlntpyarrow

about:
  home: https://github.com/tfussell/xlnt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'C++ XLSX library'
  dev_url: https://github.com/tfussell/xlnt

extra:
  recipe-maintainers:
    - tfussell
