travis:
  secure:
    BINSTAR_TOKEN: YwPk3u/YHlctxYz2bfN8NS6zGpp1zf/sCqjybmSF8hzOwxQOhWtutXpJoOogvEMykpTuBi3WB2W17uBvbiJwt+UGamD2uzn6Tg8CZer1tjZvdVUFiJtSl/AN04sSk0tLu8wPn+z8d7obnRWMPdHAC2IbI6+aF20DgXbkeUocAyVjL9nTRF4mkRhGuw84Jgh2F5ecGtrUElK+AP3T97r4TJPHd7+z512EbFF9EA1ZgcMEOYTM5iTJ5QOQ5UFCDGCm/78v130DTFStYqtwGnIhXr9SH49BoKKb48zcTnLBkOVj86BJx1SsnGcDg2d6CCpWa6/N1Fi2FfPvGOEf5lC2cna2v1r/dO9rOCXHtbylWzb08hTVJ17eBOecHopLLZQ9o/U/qfdltUvzbdgHcUtKCOtlcPaa2hmLhTUno1GkEZe1q5bnCpNLce/ISDyvmyA/qdQElRbv/9S0w+h/9AdVEAae4kempz2FzmJgvDh4/kYiW/KzxEISYokl/QjKpqmV3oKkpUkdmJp4lmsIYuf9yxZAuC+D4StD5ID0FwOaaBeJo8blE26wMP52DdRzyj2qqfsGIkaAkckcok7Eg8bRXTM0vuo78kUoCQJCmHpPbriqL7LfbOo4OUYqNsVDsqrSdO2Fg+f7oYg9F15yn0ptKxAgkdtLFOW2rn1zadnCMjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
