appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Y0BIV2gVGFUIjTM3bmG1MHKA2hYGVd4iEfYr0wsNjUWeklEC06yjTdYSAND1ZMKaSw2tkpl5+X5x7aZALz/e+rTEcB8nglmzGq0M1rEyAQYICMXhov/Vwzj2RJNaxNmUGu/jA8Y/ZI2O71cS7wPX1axfuDcUxzyM8/HVNFlJE1/tNk+firIKrIvjAE/4kVBwwEg/En5iV4wzhgJIWU0L3O1U9d9sYqOLuLTkaON/SYhr107rbjeYES5ReEnKTYRT8bAz/nJqZDJ5DXjjaq7mmYpnpA3C+4pnyOQdNH1bm9LCO3IxuAwjTbQnlxDqTHkK8CzhorhSqSXZWJEglktuB1l+4/aRkcJPZckKYxHPYyVOR/mwQFF6E01hut3m27z94ecOBS250uF42U0UTspR56Z1e+dzVPGayOXWlpzHwNIXfxNjX3aoZZuSKGSHnvFu9Q0Y4rNbgEzdxhbftb+xwSnuvMM09jODXEm9bliVtNSCepLHPcIoZG5cZO4sd3e+vmbYOLUIdjZ7IAG+Xoc4CtWp5GppdE1Ov3rdxXTfQd+9auspNdKtmcd0IKGhJ9PwnSbhcvzeRHsVSCz2WFTZfmSHTDRnLhgHnaCmKdOURjS7+hIsH+7o6ThbL+JjCO61efEEO4jWmK599LVuYhXwtuUEIkQcY7L4B28YmUvdo3Y=}
